### ISSUE TITLE
Generating event stubs when method argument types take type parameters

### ISSUE THREAD

**Issue by orfjackal** [orfjackal/jumi-actors#1]
*Jumi Actors 0.1.196*

When generating event stubs for the following DaemonListener interface:
```
public interface DaemonListener extends NetworkEndpoint<Event<SuiteListener>, Event<CommandListener>> {
}

public interface NetworkEndpoint<In, Out> {
    void onConnected(NetworkConnection connection, MessageSender<Out> sender);
    void onMessage(In message);
    void onDisconnected();
}
```

Then the following exception is thrown:
```
java.lang.IllegalArgumentException: unsupported type Out
	at fi.jumi.actors.maven.codegen.JavaType.of(JavaType.java:31)
	at fi.jumi.actors.maven.codegen.JavaType.of(JavaType.java:13)
	at fi.jumi.actors.maven.codegen.JavaType.asJavaTypes(JavaType.java:45)
	at fi.jumi.actors.maven.codegen.JavaType.typeArgumentsOf(JavaType.java:37)
	at fi.jumi.actors.maven.codegen.JavaType.of(JavaType.java:13)
	at fi.jumi.actors.maven.codegen.ArgumentList.<init>(ArgumentList.java:17)
	at fi.jumi.actors.maven.EventStubGenerator.getFrontend(EventStubGenerator.java:81)
	at fi.jumi.actors.maven.GenerateEventStubsMojo.execute(GenerateEventStubsMojo.java:105)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
```

It might be necessary for the code generator to be able to calculate the actual type parameters of the inherited methods based on the type parameters provided by the subinterface. It may get messy, unless we can find a friendly library for calculating those types...

**Comment by orfjackal** [comment]
This issue is deprecated because of the new code generator.
